apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*.yaml

build:
  artifacts:
    - image: apkwan/ticket-auth
      context: ./auth
      sync:
        manual:
          - src: 'src/**/*.{js,ts,jsx,tsx}'
            dest: .
    - image: apkwan/ticket-tickets
      context: ./tickets
      sync:
        manual:
          - src: 'src/**/*.{js,ts,jsx,tsx}'
            dest: .
    - image: apkwan/ticket-client
      context: ./client
      sync:
        manual:
          - src: 'src/**/*.{js,ts,jsx,tsx}'
            dest: .
    - image: apkwan/ticket-expiration
      context: ./expiration
      sync:
        manual:
          - src: 'src/**/*.{js,ts,jsx,tsx}'
            dest: .
    - image: apkwan/ticket-orders
      context: ./orders
      sync:
        manual:
          - src: 'src/**/*.{js,ts,jsx,tsx}'
            dest: .
    - image: apkwan/ticket-payments
      context: ./payments
      sync:
        manual:
          - src: 'src/**/*.{js,ts,jsx,tsx}'
            dest: .
  local:
    push: true