import getCurrentUser from './api/get-current-user';
import Header from '@/components/header';
import './globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser();
    
  return (
    <html lang="en">
      <body>
        <div className="container">
          <Header currentUser={currentUser} />
          {children}
        </div>
      </body>
    </html>
  )
}