import Header from '@/components/header';
import CurrUserProvider from '@/contexts/current-user-context';
import './globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <CurrUserProvider>
          <div className="container">
            <Header />
            {children}
          </div>
        </CurrUserProvider>
      </body>
    </html>
  );
}