import Header from '@/components/header';
import './globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="root-layout">  
      <Header />
      <main>{children}</main> 
      <footer>Footer</footer>
    </div>
  )
}
